### ISSUE TITLE
Deprecated fields are not generated

### ISSUE THREAD

**Issue by mediamartin** [shotor/ts-gql-sdk-gen#11]
Hi Kian can you change this line so deprecated fields won't get ignored in generating the schema. Since you still want to test fields that are going to get deprecated we still want those fields to be generated.

I can't create a pull request in this repo but if you change in src/index.ts line 52 to:

```
execSync(`${operationsGenerator} --schemaFilePath ${schemaFile} --destDirPath ${destination} --depthLimit 5 --includeDeprecatedFields`)
```

**Comment by shotor** [comment]
merged!
